export default {
  CATEGORY_CREATED: 'Category created successfully',
  CATEGORY_UPDATED: 'Category updated successfully',
  CATEGORY_DELETED: 'Category deleted successfully',
  CATEGORY_NOT_FOUND: 'Category not found',
  CATEGORY_EXISTS: 'Category already exists',
  CATEGORY_FETCHED: 'Category fetched successfully',
  CATEGORY_FETCH_FAILED: 'Failed to fetch category',
  CATEGORY_DELETE_FAILED: 'Failed to delete category',
  CATEGORY_UPDATE_FAILED: 'Failed to update category',
  CATEGORY_CREATE_FAILED: 'Failed to create category',
  SUB_CATEGORY_CREATED: 'SubCategory created successfully',
  SUB_CATEGORY_UPDATED: 'SubCategory updated successfully',
  SUB_CATEGORY_DELETED: 'SubCategory deleted successfully',
  SUB_CATEGORY_NOT_FOUND: 'SubCategory not found',
  SUB_CATEGORY_EXISTS: 'SubCategory already exists',
  SUB_CATEGORY_FETCHED: 'SubCategory fetched successfully',
  SUB_CATEGORY_FETCH_FAILED: 'Failed to fetch SubCategory',
  SUB_CATEGORY_DELETE_FAILED: 'Failed to delete SubCategory',
  SUB_CATEGORY_UPDATE_FAILED: 'Failed to update SubCategory',
  SUB_CATEGORY_CREATE_FAILED: 'Failed to create SubCategory',
  CATEGORY_ID_REQUIRED: 'Category ID is required',
};
